-- 코드를 입력하세요
SELECT
    b.AUTHOR_ID,
    a.AUTHOR_NAME,
    b.CATEGORY,
    SUM(bs.TOTAL_BOOK_SALES * b.PRICE) AS TOTAL_SALES
FROM BOOK b
JOIN AUTHOR AS a ON b.AUTHOR_ID = a.AUTHOR_ID
JOIN(
    SELECT
    BOOK_ID,
    SUM(SALES) AS TOTAL_BOOK_SALES
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01%'
    GROUP BY BOOK_ID
) AS bs ON bs.BOOK_ID = b.BOOK_ID
GROUP BY b.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY
ORDER BY b.AUTHOR_ID ASC, b.CATEGORY DESC;