-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, SUM(p.PRICE * OFF.SALES_AMOUNT) AS SALES
FROM PRODUCT p
JOIN OFFLINE_SALE AS OFF ON p.PRODUCT_ID = OFF.PRODUCT_ID
GROUP BY p.PRODUCT_CODE
ORDER BY SALES DESC, p.PRODUCT_CODE ASC;