-- 코드를 입력하세요
SELECT a.ANIMAL_ID, a.ANIMAL_TYPE, a.NAME
FROM ANIMAL_INS a
JOIN ANIMAL_OUTS AS o ON a.ANIMAL_ID = o.ANIMAL_ID
WHERE a.SEX_UPON_INTAKE LIKE 'intact%'
AND (o.SEX_UPON_OUTCOME LIKE 'Spayed%' OR o.SEX_UPON_OUTCOME LIKE 'Neutered%');