-- 코드를 입력하세요
# SELECT a.ANIMAL_TYPE, COUNT(*) AS 'count'
# FROM ANIMAL_INS a
# WHERE a.ANIMAL_TYPE IN ('Cat', 'Dog')
# GROUP BY a.ANIMAL_TYPE
# ORDER BY a.ANIMAL_TYPE ASC;

SELECT ANIMAL_TYPE, count(*)
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE;


